### ISSUE TITLE
serving from a folder instead of a .model file

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#177]
Why can't I serve from a folder?
I think that it makes sense to have this option. The main reason is that if you're making a new model, you're constantly fiddling with things. If you have to export it every single update, it is a huge waste of effort, and you end up making a new folder every time the server extracts the model archive. 

You should be able to drop the `.model` and just point to a folder like:

```
mxnet-model-server --models squeezenet=squeezenet_v1.1
```

Also, think about this: you first download one via s3, then serve it, then go in and tinker with the settings. Then you export it and it overwrites the original model. Oops. Then you serve it and it overwrites the directory with the original files. Oops. It doesn't work (because reasons), so you pull the original down and serve it, and that overwrites your changes in the folder. Oops again.

**Comment by lupesko** [comment]
I can see the validity of the use case.
Let's mark as an enhancement.

**Comment by yuruofeifei** [comment]
https://github.com/awslabs/mxnet-model-server/pull/240
