### ISSUE TITLE
Windows: running mxnet-model-server for first time is very slow

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#185]
It hangs for at least a minute. I thought it was totally broken, so I killed the Python process to get my prompt back.

Not sure if this is something related to being on an AMI. I notice that the first time you fire up the frameworks there is a significant lag. However, this is way too long. Everyone will assume it is broken.

Is it possible to give immediate user feedback? Like "Loading..." or "Hang tight..."?

**Comment by frankfliu** [comment]
MMS 1.0 working fine with widows.
