### ISSUE TITLE
model server description and new manifest info

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#188]
I expected there to be some impact to the API description from the new manifest. 
When you hit http://localhost:8080/api-description I'd think that the `title` should be updatable, but that's not listed in the manifest. Model-Archive-Description is the closest. 

One big reason is that when you do the client API generation with Swagger you're going to get stuck with that name. Then when you go to publish the package to npm, it's going to say "Model Serving Apis" and it's not clear how you change that.

## What happens
My javascript api client is hardcoded with `Model Serving Apis`.
My api-description is hardcoded with `Model Serving Apis` for the `title`.

## What's expected
It should pull that data from the manifest. Probably the  Model-Archive-Description, but it would be better if the naming conventions matched.

## Other related issues
1. Also the version number didn't seem to be updated by anything in the manifest. You'd think the 1.0.0 would be the Model-Archive-Version... something that the user can tinker with.  

1. On that note, it's kind of weird to have the user putting in the manifest data about Model-Server when they have no idea which `server` or `engine` version it is.  

1. Shouldn't that be `Created By`... `Model-Export` instead of server? 

1. This kind of data would be something you'd see in the api-description end-point, some passed in from the manifest, some generated internally by MMS, and maybe MMS provides manifest template for you, so you don't screw it up by cloning data from an older model by example.

```
  "description": {
    "host": "127.0.0.1:8080", 
    "info": {
      "title": "Model Serving Apis", 
      "version": "1.0.0"
```

```
    "Model-Archive-Version": 0.1,
    "Model-Archive-Description": "SqueezeNet Model",
    "License": "Apache 2.0",
    "Created-By": {
        "Model-Server": 0.2,
        "Author": "mxnet-sdk",
        "Author-Email": "mxnet-sdk-dev@amazon.com"
    },
    "Model": {
        "Parameters": "squeezenet_v1.1-0000.params",
        "Symbol": "squeezenet_v1.1-symbol.json",
        "Signature": "signature.json",
        "Description": "SqueezeNet v1.1",
        "Model-Format": "MXNet-Symbolic",
        "Model-Name": "squeezenet_v1.1",
        "Service": "mxnet_vision_service.py"
    },
    "Engine": {
        "MXNet": "0.12.1"
    }
```

**Comment by frankfliu** [comment]
client generation is longer supported in MMS 1.0.
User can save api-descriptor output, modify it and then use Swagger to generate their client code.
