### ISSUE TITLE
exporter not adding files to subdirectory

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#207]
It's not getting files in folders like "assets".

**Comment by lupesko** [comment]
I'm not sure why we really need an "asset" folder - why not just flatten everything in the root?
@yuruofeifei - please chime in.

**Comment by nswamy** [comment]
I don't think we need assets folder. but if the user provides a folder with subfolders I would expect that to be present in the exported model as well so I don't have to write different code for the package model and when i am developing the service.

**Comment by lupesko** [comment]
Agreed!
Current behavior seem to be that mxnet-model-export just ignores nested folders. We need to fix that.

**Comment by yuruofeifei** [comment]
Unfortunately decompressing zip files requires random access to the archive, and the ZipFile methods (not to mention the DEFLATE algorithm itself) only provide streams. It is therefore impossible to decompress nested zip files without extracting them.

https://stackoverflow.com/questions/11930515/unzip-nested-zip-files-in-python
