### ISSUE TITLE
duplicate warning when using service file without the --service option

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#209]
(mxnet3.6) 8c8590217d26:squeeze markhama$ mxnet-model-export --model-name squeeze1 --model-path .
/Users/markhama/Development/mxnet3.6/lib/python3.6/site-packages/mms/export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py:1355: UserWarning: Duplicate name: 'mxnet_vision_service.py'
  return self._open_to_write(zinfo, force_zip64=force_zip64)

**Comment by yuruofeifei** [comment]
It is fixed #240
