### ISSUE TITLE
Validate all files used by the default service that we pack in the archive

### ISSUE THREAD

**Issue by nswamy** [awslabs/mxnet-model-server#225]
Vision Service uses synset, Xporter should validate if the synset.txt exists in the `model-path`

**Comment by lupesko** [comment]
This is more of a generic problem that goes beyond the Vision Service.
How would the `model-server-export` know what files are used by the custom code?

Not sure if we need to handle this case, but rather clarify this is the responsibility of the user exporting a package.

**Comment by nswamy** [comment]
we provide vision and base service as default handlers I would assume you also know what files are mandatory for these services and fail the export if they are not provided.

**Comment by lupesko** [comment]
OK, makes sense.

**Comment by yuruofeifei** [comment]
Currently, vision service is default
