### ISSUE TITLE
mxnet_model_service.py not using synset in post_process

### ISSUE THREAD

**Issue by nswamy** [awslabs/mxnet-model-server#227]
mxnet_model_service reads the synset if it is available but does not use it in postprocess

**Comment by lupesko** [comment]
@nswamy can you specify the expected behavior?

**Comment by nswamy** [comment]
it is suppose to show the labels(assuming this to be classification task) if a synset is available in the archive

**Comment by nswamy** [comment]
Ass

**Comment by yuruofeifei** [comment]
It is used here:
https://github.com/awslabs/mxnet-model-server/blob/master/mms/model_service/mxnet_vision_service.py#L37
