### ISSUE TITLE
Make Docker images available in container registries

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#231]
- Docker Hub
- ECS Registry
- Anything else?

**Comment by yuruofeifei** [comment]
I think thats all.

**Comment by lupesko** [comment]
Maybe document an example usage/setup in /docs?

**Comment by lupesko** [comment]
Available, work done by @vdantu @ankkhedia :
https://hub.docker.com/r/awsdeeplearningteam/mms_cpu/
https://hub.docker.com/r/awsdeeplearningteam/mms_gpu/

Closing.
