### ISSUE TITLE
Post method in python code

### ISSUE THREAD

**Issue by Heidisnaps** [awslabs/mxnet-model-server#235]
Hello.
How to use post in python code instead of "curl -X post"?
For example, is there a way to post like this?
http://127.0.0.1:8080/squeezenet/predict/Users/Download/cat.jpg

**Comment by lupesko** [comment]
There's different ways to do it in Python... [urllib](https://docs.python.org/3.5/library/urllib.request.html) is one.

Curious to understand the use case you have in mind...

**Comment by Heidisnaps** [comment]
@lupesko 
thanks!!

**Comment by Heidisnaps** [comment]
@lupesko 
Hello. I tried importing 'requests', 'urllib' with your advice, but it does not work.
It is as follows.
```
img_path ='/Users/Download/kitten.jpg'
files = {'image/jpeg': open(img_path, 'rb')}
requests.post('http://127.0.0.1:8080/squeezenet/predict', files=files)
>>><Response [400]>
```
Please help me.

**Comment by lupesko** [comment]
Actually, Model Server handles this for you with the gen-api feature.
Gen-api can generate the client code for you in most high level languages, including Python.

To use it, follow these steps:
1. Generate client code for python using mxnet-model-server as detailed [here](https://github.com/awslabs/mxnet-model-server/blob/master/docs/code_gen.md)
1. See that a `/build` directory was created where you executed the model server command - this dir contains the auto generated client code
1. cd into the /build dir
1. Install the package, e.g. `python setup.py install --user`
1. Start the python shell, and then:
```python
import swagger_client.apis as api
client = api.DefaultApi()
client.ping()
# You should see {'health': 'healthy!'}, or otherwise your server is probably not running...
client.squeezenet_predict("<file path>") # change the method name per the model name you are using
# You should see the prediction result
```

If you are interested to see the auto-gen python code, and how it is posting the file, you can always look into the generated code.

HTH!
Hagay
