### ISSUE TITLE
Onnx support

### ISSUE THREAD

**Issue by yuruofeifei** [awslabs/mxnet-model-server#236]
Onnx support for model server with exporter

**Comment by lupesko** [comment]
We'd like to have the following capabilities:
- Be able to package up ONNX model with mxnet-model-export
- Be able to run inference on a model packaged with ONNX model and code.

Open question: when do we do the ONNX -> MXNet import? at export time, or at serve time?
@yuruofeifei @sandeep-krishnamurthy @nswamy @jesterhazy @Roshrini - thoughts?

**Comment by nswamy** [comment]
it makes sense to do it at the export time, so we can decouple conversion from serving. Model Server can assume that it will get a packaged archive. Exporter can use onnx-mxnet converter and use existing logic to create the archive.

**Comment by yuruofeifei** [comment]
Agreed with @nswamy, it is better to decouple conversion from serving.

**Comment by yuruofeifei** [comment]
https://github.com/awslabs/mxnet-model-server/pull/240
