### ISSUE TITLE
Wrong custom service class definition when the name is sorted before 'MXNetVisionService'

### ISSUE THREAD

**Issue by windsorwho** [awslabs/mxnet-model-server#239]
https://github.com/awslabs/mxnet-model-server/blob/f98a2763f71695a59a69974c367c6f8e43203373/mms/mxnet_model_server.py#L150

The assumption that "# The overrided class is the last one in class_defs" is wrong because 'class_defs' is a list returned by inspect.getmembers(), which returns a list of member classes names sorted by the name. 
https://docs.python.org/2/library/inspect.html#inspect.getmembers

So, using "mode_class_name = class_defs[-1].__name__" leads to wrong class name when the class name string is something smaller than the base class name.

Thanks.

**Comment by lupesko** [comment]
@windsorwho good call. Did this cause an issue for you? if so - can you provide the example?
@yuruofeifei can you take a look?

**Comment by yuruofeifei** [comment]
@windsorwho, thank you for pointing this out!

@lupesko, I will take a look!
