### ISSUE TITLE
ONNX Support: need to have all ONNX model zoo models are able to be exported

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#245]
We need to have all models from [ONNX Model Zoo](https://github.com/onnx/models) be able to be exported to a Model Archive.

If needed, we need to contribute fixes to [ONNX-MXNet](ONNX-MXNet) repo.

This is a launch blocker.

**Comment by yuruofeifei** [comment]
https://s3.amazonaws.com/model-server/models/onnx-vgg19/vgg19.onnx
https://s3.amazonaws.com/model-server/models/onnx-inception_v1/inception_v1.onnx
https://s3.amazonaws.com/model-server/models/onnx-alexnet/alexnet.onnx
https://s3.amazonaws.com/model-server/models/onnx-squeezenet/squeezenet.onnx

**Comment by aaronmarkham** [comment]
I've exported the four above and uploaded them to S3.
