### ISSUE TITLE
unable to export a model from an ONNX file

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#249]
Attempting to run:
```
mxnet-model-export --model-name squeezenet_v1.1 --model-path . --from-type onnx
```
Results in error:
```
AssertionError: should have 1 onnx file ending with *.onnx in the filename, given:[] in model_path:squeezenet.onnx
```
There definitely is a .onnx file there. I tried variations on the dot by calling out the file directly and I get the same error. I built from source.

**Comment by yuruofeifei** [comment]
Can you provide more details? you have to put the model under the model-path

**Comment by yuruofeifei** [comment]
Maybe you can try the latest one after my PR is merged, onnx is auto infer now.

**Comment by lupesko** [comment]
Might be fixed once #248 is in?
Assigning to @yuruofeifei to look into.

**Comment by lupesko** [comment]
I was able to test it with the latest version and it is working.

**Comment by lupesko** [comment]
Confirmed with @aaronmarkham - it is fixed.
