### ISSUE TITLE
pip install fails due to missing protobuf dependency

### ISSUE THREAD

**Issue by jesterhazy** [awslabs/mxnet-model-server#251]
fresh install of model server 0.2 fails due to missing protobuf dependency. dependency is indirect, introduced by onnx-mxnet package.

we should update our docs to include the prerequisite.

```
$  pip install -U -e .
Obtaining file: ...
Collecting mxnet>=1.0 (from mxnet-model-server==0.2)

...

Collecting onnx>=0.2 (from onnx-mxnet>=0.2->mxnet-model-server==0.2)
  Downloading onnx-1.0.0.tar.gz (763kB)
    100% |████████████████████████████████| 768kB 1.7MB/s 
    Complete output from command python setup.py egg_info:
    fatal: Not a git repository (or any of the parent directories): .git
    Could not find "protoc" executable!
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/nz/57cdgtr11pdg01rgzyzhjxvmqwmxjn/T/pip-build-fltlXV/onnx/
```

**Comment by Roshrini** [comment]
This dependency is required by onnx package.
On Linux 16, you can install protobuf compiler like this:
sudo apt-get install protobuf-compiler libprotoc-dev

**Comment by Roshrini** [comment]
On Mac:
conda install -c conda-forge protobuf

We can probably just point to onnx repo for protobuf installation instructions.

**Comment by jesterhazy** [comment]
yes, i think we just need to mention it in the instructions
