### ISSUE TITLE
install from source instructions should use pip

### ISSUE THREAD

**Issue by jesterhazy** [awslabs/mxnet-model-server#252]
in README.md, the install from source instructions should use pip instead of setup_tools. e.g. instead of:

`sudo python setup.py install`

we should have:

`pip install -U` (and optionally mention `-e`)

installing this way will be more consistent with pip install of pypi package.

**Comment by aaronmarkham** [comment]
I've found that the pip packages are usually not fully current (lagging sometimes by days), so doing a `git pull` followed by a `python setup.py install` is the way to go.

It would be great to provide some more transparency on that so it's easy be able to install the latest stuff versus the most recent package.

**Comment by jesterhazy** [comment]
`pip install -U .` will install and upgrade from current project directory. `pip install -U -e .` will install current directory in "editable" mode. We should prefer these over setup.py.
