### ISSUE TITLE
fix importlib deprecation warning under python3

### ISSUE THREAD

**Issue by jesterhazy** [awslabs/mxnet-model-server#254]
$ mxnet-model-export --model-name squeezenet_v1.1 --model-path .

/usr/local/anaconda3/envs/mms3/lib/python3.6/site-packages/mms/export_model.py:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

**Comment by yuruofeifei** [comment]
fixed by #279
