### ISSUE TITLE
Importing ONNX models that have .pb suffix

### ISSUE THREAD

**Issue by pracheer** [awslabs/mxnet-model-server#257]
The models on onnx [github](https://github.com/onnx/models) page are tar files. When untarred, there is an .pb file (and few .npz files). We have to currently rename the file to .onnx in order to make it work.

**Comment by lupesko** [comment]
After discussing with the contributors, here's the definition of what we want to do:
- Supported extensions: *.onnx for ONNX format, *.params+*.json for MXNet format
- We return an error in case: (1) there is a mix of the above (2) none is there

@aaronmarkham to provide the error text

**Comment by aaronmarkham** [comment]
Here's some error text:

if count(*.params||*.onnx||*symbol.json)<1 :
~
mxnet-model-export supports the exporting of MXNet and ONNX models to a mxnet-model-server .model file. MXNet models are expected as two files in the same directory, a params file and a symbol file, both with the same prefix (a common name) and where 0000 is the param's epoch number (any number from 0 to n). Example: modelname-0000.params and modelname-symbol.json. ONNX models are expected as one file. Example: modelname.onnx. See https://github.com/onnx/onnx for converting PyTorch, Caffe2, CNTK, and other models to the ONNX format.
~

if count(*.params||*.onnx||*symbol.json)>1 : (obviously some other variations here)
~
More than the appropriate number of model artifacts were detected in the folder provided, %s. 
~continued to next check...

if count(*.onnx>1):
~
mxnet-model-export expects only one .onnx file. Please supply the single model file you wish to export.
~

if count(*.params>1):
~
mxnet-model-export expects only one modelname-0000.params file. Please supply the single parameter file you wish to export.
~

if count(*symbol.json>1):
~
mxnet-model-export expects only one modelname-symbol.json file. Please supply the single parameter file you wish to export.
~end file quantity checks

if (\regex\check for 0000\ in *.params):
~
When exporting an MXNet model, mxnet-model-export expects a parameters file that designates the epoch number in the filename. 0000 is usually sufficient, but if known, you can supply any epoch number in the format: modelname-1234.params. The number can be as large as whatever the MXNet Engine you are using supports.
~

if (modelname in *.params != modelname in *symbol.json):
~
You parameters file and symbols file naming prefix do not match. When exporting an MXNet model, mxnet-model-export expects two files in the same directory, a params file and a symbol file, both with the same prefix (a common name) and where 0000 is the param's epoch number (any number from 0 to n). Example: modelname-0000.params and modelname-symbol.json. 
~

For bonus points for solving #277:
if (onnx) && (data_name in signature.json != "input_0"):
~
You are attempting to export an ONNX model, but your signature.json file does not contain the required "data_name". "data" was found in the "data_name" value. When serving an ONNX-sourced model, mxnet-model-server expects to find a "data_name" of "input_0". Adjust your signature.json file and try again.
~

I'd really like to add a link to exporting an MXNet model, but we don't have one on the site AFAIK.
I wrote one a while back, but I was using Gluon and we didn't support Gluon yet. Has that changed? If so, I'd like to publish a tutorial for that...

**Comment by jesterhazy** [comment]
@aaronmarkham in you last comment above, did you mean exporting a gluon model?

**Comment by jesterhazy** [comment]
fixed in #295
