### ISSUE TITLE
A better error response from server if the image is not valid jpg type

### ISSUE THREAD

**Issue by gautamkmr** [awslabs/mxnet-model-server#261]
hello.jpg is not a valid jpg format. 

(python3) ubuntu@ip-172-31-9-27:~$ curl -X POST http://127.0.0.1:8081/squeezenet/predict  -H "ContentType:image/jpeg" -v  -F "data=@hello.jpg" 
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 8081 (#0)
> POST /squeezenet/predict HTTP/1.1
> Host: 127.0.0.1:8081
> User-Agent: curl/7.55.1
> Accept: */*
> ContentType:image/jpeg
> Content-Length: 11003
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------40da753a16522fe1
> 
< HTTP/1.1 100 Continue
* HTTP 1.0, assume close after body
< HTTP/1.0 500 INTERNAL SERVER ERROR
< Content-Type: text/html
< Content-Length: 188
< Access-Control-Allow-Origin: *
< Server: Werkzeug/0.14.1 Python/3.6.3
< Date: Thu, 11 Jan 2018 20:37:59 GMT
< 
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>Error occurs while inference was executed on server.</p>
* Closing connection 0
(python3) ubuntu@ip-172-31-9-27:~$

**Comment by frankfliu** [comment]
Fixed in MMS 1.0
