### ISSUE TITLE
Put an index.html instead of 404 error message at the root of the MMS web-server

### ISSUE THREAD

**Issue by bhavinthaker** [awslabs/mxnet-model-server#268]
After I started the MMS server, here is the message in the log file on stdout:

[INFO 2018-01-11 12:47:30,488 PID:56822 /Users/thakerb/anaconda3/envs/mms_feb_2018_1/lib/python3.6/site-packages/mms/mxnet_model_server.py:start_model_serving:109] Service description endpoint: 127.0.0.1:8080/api-description
[INFO 2018-01-11 12:47:30,489 PID:56822 /Users/thakerb/anaconda3/envs/mms_feb_2018_1/lib/python3.6/site-packages/mms/mxnet_model_server.py:start_model_serving:110] Service health endpoint: 127.0.0.1:8080/ping
[INFO 2018-01-11 12:47:30,501 PID:56822 /Users/thakerb/anaconda3/envs/mms_feb_2018_1/lib/python3.6/site-packages/werkzeug/_internal.py:_log:88]  * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)

However, my eyes only saw the last line and so I tried to access: http://127.0.0.1:8080/ for which I got the 404 error. 

I would suggest having an index.html file with a welcome message at the top-level relative root folder of the web-server so that users do NOT get the 404 error.

**Comment by vrakesh** [comment]
fixed in pr #359
