### ISSUE TITLE
Documentation: Make the intent explicit on download the cute cat image.

### ISSUE THREAD

**Issue by bhavinthaker** [awslabs/mxnet-model-server#269]
Suggestion:

Change the documentation
FROM:
"To test it out, download a cute picture of a kitten and name it kitten.jpg. Then run the following curl command to post an inference request with the image. In the example below both of these steps are provided."

TO:
"To test it out, download a cute picture of a kitten and name it kitten.jpg using the wget command below. Then run the following curl command to post an inference request with the image. In the example below both of these steps are provided."

Add the text: "using the wget command below". I actually downloaded the image I was doing steps sequentially -- this was not needed since the wget commands does it. :-)

**Comment by jesterhazy** [comment]
thx we'll try to make this clearing
