### ISSUE TITLE
Suggestion: use --start and --stop for starting the MMS server

### ISSUE THREAD

**Issue by bhavinthaker** [awslabs/mxnet-model-server#270]
Add a --start and --stop options to start and stop the server instead of using Ctrl-C which can get lost in the log-file and not having the stop interface documented in the usage. 

Make the product intuitive to use without relying on tribal knowledge.

**Comment by jesterhazy** [comment]
@bhavinthaker when you run `mxnet-model-server` directly from the command line, you are essentially running in dev/debug mode (debug mode app server, logging to console, etc.). running in the foreground and using control-c to exit is pretty common for this scenario.

are you saying it would be better to run dev/debug mode as a background process and use start/stop commands to contorl it, or is this more about how we would run mms as a (production) service?

**Comment by lupesko** [comment]
No feedback from requester, closing.
Feel free to reopen if done in error.
