### ISSUE TITLE
Fix the usage to make it understandable

### ISSUE THREAD

**Issue by bhavinthaker** [awslabs/mxnet-model-server#272]
1) Change usage : The input statement is confusing to understand.
FROM:
  --service-file-path SERVICE_FILE_PATH
                        Service file path to handle custom MMS inference
                        logic. if not provided, this tool will package
                        MXNetBaseService if input in signature.json is
                        application/json or MXNetVisionService if input is
                        image/jpeg
TO:
  --service-file-path SERVICE_FILE_PATH
                        Service file path to handle custom MMS inference
                        logic. If not provided, this tool will package
                        MXNetBaseService. If input in signature.json is
                        application/json or MXNetVisionService if input is
                        image/jpeg  (well, I am not sure what exactly the message is!)

2) Include --help in the usage
FROM:
usage: mxnet-model-export [-h] --model-name MODEL_NAME --model-path MODEL_PATH
                          [--service-file-path SERVICE_FILE_PATH]
TO:
usage: mxnet-model-export [-h|--help] --model-name MODEL_NAME --model-path MODEL_PATH
                          [--service-file-path SERVICE_FILE_PATH]

**Comment by aaronmarkham** [comment]
This is actually in the app code for its `--help` output.
