### ISSUE TITLE
CloudWatch metrics feature issues

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#274]
Users of CloudWatch feature should be able to:
- Monitor all metrics per host
- Monitor all metrics per model (across hosts)

Currently they cannot. Let's please make a better use of the [CloudWatch BOTO API] (http://boto3.readthedocs.io/en/latest/reference/services/cloudwatch.html) so:
- Use Dimensions to capture the ModelName and the HostName (two different dimensions)
- Use StatisticValues to capture statistical info such as latencies (*_latency)
- We’re missing a postprocess_latency – let’s please add it
- Let’s please use the namespace “ModelServer/”
- Let's please differentiate 4XX errors from 5XX errors

@jesterhazy @nswamy @yuruofeifei for feedback and suggestions

**Comment by jesterhazy** [comment]
also fix typo in mxnet-model-server.py mode_name -> model_name

**Comment by jesterhazy** [comment]
latencies are currently measured in seconds, which isn't too helpful. let's change to milliseconds.

**Comment by jesterhazy** [comment]
how is memory metric calculated?

`memory for last 30 seconds is 0.006215, writing to AWS CloudWatch...`

this is with 16GB total memory, mms python process using 106MB.

**Comment by jesterhazy** [comment]
how are latencies calculated? it looks like a sum of latencies over last reporting window, which isn't useful. we should discuss correct reporting for these values.

if we report as individual data points (a list of latencies per CW call), then users can use standard CW aggregation to get useful stats like min/max/mean/med and percentiles.

if we want to report fewer datapoints, then we could collect our own summary stats, but then we'd need to choose some useful summary metrics, and report each of them separately. I prefer the separate data points approach. See https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/PublishMetrics.html for some background

**Comment by jesterhazy** [comment]
+1 to separating 4XX 5XX errors

**Comment by jesterhazy** [comment]
for the namespace, i think we should stay aligned with the product name. That would give us 'MXNetModelServer'

**Comment by lupesko** [comment]
> latencies are currently measured in seconds, which isn't too helpful. let's change to milliseconds.

Agreed we need to report ms, but beyond that we should use proper units for every metric we're reporting. CloudWatch API supports pretty extensive units:
`'Unit': 'Seconds'|'Microseconds'|'Milliseconds'|'Bytes'|'Kilobytes'|'Megabytes'|'Gigabytes'|'Terabytes'|'Bits'|'Kilobits'|'Megabits'|'Gigabits'|'Terabits'|'Percent'|'Count'|'Bytes/Second'|'Kilobytes/Second'|'Megabytes/Second'|'Gigabytes/Second'|'Terabytes/Second'|'Bits/Second'|'Kilobits/Second'|'Megabits/Second'|'Gigabits/Second'|'Terabits/Second'|'Count/Second'|'None',`

This should be used properly.

**Comment by lupesko** [comment]
@yuruofeifei I think there's enough discussion here that warrants a quick tech writeup to clearly articulate:
- Functional goals (mentioned start of issue)
- How we're collecting metrics (design of classes/modules and algo for collection)
- How we're reporting metrics (API, units, statistics)
