### ISSUE TITLE
UserWarning: Attribute axis is disabled in sym.broadcast_add

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#275]
Running:
```
mxnet-model-export --model-name squeezenet_v1.1 --model-path .
```
Gives you the warning:
```
/Library/Python/2.7/site-packages/onnx_mxnet-0.3.1-py2.7.egg/onnx_mxnet/common.py:97: UserWarning: Attribute axis is disabled in sym.broadcast_add
```
It's not clear if the export is fully successful or not.

**Comment by aaronmarkham** [comment]
Upon testing the exported model, it does not handle inference. Uploading a jpeg image results in the error:
```
8c8590217d26:dms markhama$ curl -X POST http://127.0.0.1:8080/squeezenet/predict -F "data=@kitten.jpg"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>must be string or buffer, not None</p>
```

**Comment by Roshrini** [comment]
@aaronmarkham 
```
/Library/Python/2.7/site-packages/onnx_mxnet-0.3.1-py2.7.egg/onnx_mxnet/common.py:97: UserWarning: Attribute axis is disabled in sym.broadcast_add
```

This is just a warning, it shouldn't affect the exported model(Coming from onnx-mxnet package). I didn't get the other error you mentioned when I tried this model in bug bash.

**Comment by aaronmarkham** [comment]
Rename this file to .model and try it out. I was able to get it to work by resetting the service file and was able to get it to "destabilize" by pointing the service to another file in a different folder:
`--service ../mxnet-model-server/mms/model_service/mxnet_vision_service.py`

[squeezenet_v1.1.zip](https://github.com/awslabs/mxnet-model-server/files/1632810/squeezenet_v1.1.zip)

**Comment by jesterhazy** [comment]
i opened up the model you provided, and noticed that the `signature.json` file includes

``` 
"inputs": [
    {
      "data_name": "input_0",
...
```

if i load that model, i can get valid predictions using the command:

`curl -X POST http://127.0.0.1:8080/squeezenet/predict -F "input_0=@kitten.jpg"`

that is, it works if the input name in the curl command matches the data name in the signature file.

**Comment by jesterhazy** [comment]
this model also gives a warning on load:

`[WARNING 2018-01-15 15:14:31,830 PID:75588 /usr/local/anaconda3/envs/mms27/lib/python2.7/site-packages/mms/model_service/mxnet_model_service.py:__init__:94] Failed to parse epoch from param file, setting epoch to 0`

this is because the model name in the manifest doesn't quite match the file names:
```
    "Model": {
        "Description": "squeezenet_v1.1", 
        "Service": "mxnet_vision_service.py", 
        "Symbol": "squeezenet-symbol.json", 
        "Parameters": "squeezenet-0000.params", 
        "Signature": "signature.json", 
        "Model-Name": "squeezenet_v1.1", 
        "Model-Format": "MXNet-Symbolic"
    }
```

**Comment by aaronmarkham** [comment]
Moving this to https://github.com/onnx/onnx-mxnet/issues/15 for the warning message described in this issue's title.
Created a new issue #277 for the `data_name` / signature.json validation issue that popped up while debugging.
