### ISSUE TITLE
validate export and/or serving and better error messaging for onnx-exported models

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#277]
The `signature.json` file describes the `data_name`, and if you put in some arbitrary value, you can get an export from an onnx model. However, the serving step will fail because it is looking for `input_0`. This relationship wasn't specified in the docs (as of yet). The user will get the error:
```
(mxnet_p36) 8c8590217d26:onnx markhama$ mxnet-model-server --models o=o.model
[INFO 2018-01-15 17:09:57,821 PID:45329 /Users/markhama/Development/mxnet_p36/lib/python2.7/site-packages/mxnet_model_server-0.2-py2.7.egg/mms/mxnet_model_server.py:__init__:94] Initialized model serving.
[WARNING 2018-01-15 17:09:57,887 PID:45329 /Users/markhama/Development/mxnet_p36/lib/python2.7/site-packages/mxnet_model_server-0.2-py2.7.egg/mms/model_service/mxnet_model_service.py:__init__:94] 
Failed to parse epoch from param file, setting epoch to 0
[ERROR 2018-01-15 17:09:57,897 PID:45329 /Users/markhama/Development/mxnet_p36/lib/python2.7/site-packages/mxnet_model_server-0.2-py2.7.egg/mms/mxnet_model_server.py:_arg_process:185] 
Failed to process arguments: You created Module with Module(..., data_names=[u'onnx']) 
but input with name 'onnx' is not found in symbol.list_arguments(). 
Did you mean one of:
	input_0
	param_0
....more layers...
```

## Expected behavior

I'd expect that if the server was going to fail when I provide anything other than `input_0`, that the exporter would have warned me that my signature was invalid... or just update it for me. Also, since there is a tight relationship on how you POST data, I would like to know that this change is required, otherwise I'd never get an onnx-exported model to serve.

This also means that I'd expect the error message coming from a "bad" POST to be more revealing. I don't think we need to obfuscate it.

```
8c8590217d26:test markhama$ curl -X POST http://127.0.0.1:8080/squeezenet/predict -F "data=@kitten.jpg"
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>expected bytes-like object, not NoneType</p>
```
Something like: 
```
This end point, squeezenet, is expecting a data_name of input_0.
End point details can be found here: http://127.0.0.1:8080/squeezenet/api-description
```

**Comment by lupesko** [comment]
Good call!
There can be one or more input nodes with arbitrary names. Currently, ONNX input node names are hard coded to input_{d}. In MXNet models this depends on the name the user is specifying for the input layer.

I agree with @aaronmarkham suggestion to make the following change:
Update the 400 error <p> node to state something like what Aaron suggested:
```
This end point, squeezenet, is expecting a data_name of input_0.
End point details can be found here: http://<host>:<port>/api-description
```

**Comment by aaronmarkham** [comment]
Two loose ends here:

* **name vs data_name in the docs**: According to https://github.com/awslabs/mxnet-model-server/blob/master/docs/rest_api.md the spec refers to "name", not "data_name". So if we give an error telling the user their data_name is bad and to refer to the docs, there's no reference to data_name on that page. Maybe the api description endpoint is out of date and showing an old name for "name". Or the doc's version of the output is out of date.

* **validate the artifacts**: The 400 error should be updated, but I also think we should try to catch this problem earlier, during the export process. Why not validate the artifacts? Check the signature, then peek in the model file to see if the layer/data_name exists for both the input and output layers.

**Comment by lupesko** [comment]
@vdantu @ankkhedia - guys can you consider this for v0.3?

**Comment by ankkhedia** [comment]
@lupesko The 400 error has been updated now and as @aaronmarkham mentioned the  the doc needs to be fixed . We will do that

**Comment by ankkhedia** [comment]
@lupesko Can you take a look at the second comment added by @aaronmarkham (validate the artifacts). As a part of it 400 error is already updated, but what do you think about  the rest?

**Comment by frankfliu** [comment]
With new model archive 1.0 spec, signature.json is no longer supported. It's model author's responsibility to handle input invalidation.
