### ISSUE TITLE
Measure post process latency in next release

### ISSUE THREAD

**Issue by yuruofeifei** [awslabs/mxnet-model-server#289]
Currently because MXNet symbol is lazy evaluated and the trigger action(eg. asnumpy()) is in the post process method, we don't have a good way to separate inference time and post processing time. 
In next release, we need fix it.

**Comment by vdantu** [comment]
Sure. Will do. We will look into profiling this for docker version.

**Comment by ddavydenko** [comment]
This is no longer relevant for MMS v1.0 as there is no pronounced support for separate pre- and post-processing.
