### ISSUE TITLE
Model Server PyPi install fails when git is not installed 

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#292]
This seems to be due to a bug on ONNX 1.0 install, which has a bug in the PyPi setup.
Filed a PR in ONNX repo: https://github.com/onnx/onnx/pull/430

We'll need to work with the ONNX team to release a patch version that fixes this. Filed an issue here: https://github.com/onnx/onnx/issues/432

Marking as a blocker.

**Comment by yuruofeifei** [comment]
It is merged by FB, I will test it.

**Comment by lupesko** [comment]
Published [ONNX 1.0.1 pre-release](https://github.com/onnx/onnx/releases/tag/untagged-e72ba16f78bee7779041)

ETA for publishing the release (if no issues) is Jan 26 1pm PT

**Comment by lupesko** [comment]
ONNX 1.0.1 release, closing.
