### ISSUE TITLE
Race condition when multiple gunicorn worker download models with same name

### ISSUE THREAD

**Issue by yuruofeifei** [awslabs/mxnet-model-server#300]
In our docker container, when multiple gunicorn worker download same models from S3 to disk, there will be read-write race condition because models are with the same name.

My proposal to fix it is adding a new optional argument: extract-to (Recommendation?) where the model will be saved and extracted to. 
Then we can create directory including gunicorn worker pid so models are separate across workers. It won't affect our current local serving flow but just requires some doc changes.
This argument would also be helpful if someone want to extract the model in different location rather than cwd.

**Comment by yuruofeifei** [comment]
@jesterhazy @lupesko @aaronmarkham appreciate your feedback.

**Comment by jesterhazy** [comment]
we need to fix this in a way that eliminates the duplicated work. 

given the current startup sequence, the most straightforward way to do this would to have only one of the model server workers do the download / extract part of the model loading.

we can use the fasteners to do this... specifically the \@fasters.interprocess_locked() decorator. 

factor the relevant part of _extract_model out into its own method, and wrap that method in the  \@fasters.interprocess_locked() decorator. add checks for model existence just outside and again inside the lock boundary (i.e. double-checked locking).

**Comment by yuruofeifei** [comment]
I like this idea @jesterhazy , It won't affect any flow right now.

**Comment by yuruofeifei** [comment]
Fixed via #302

**Comment by jesterhazy** [comment]
fixed by #302
