### ISSUE TITLE
Container deployment may require warm up as a startup custom action

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#324]
Inference executed immediately after docker image startup may run slowly due to the "cold start" effect. We would like to help MMS users avoid this slow down by helping them warm up the container.

The ask is to provide a way that:
- Automates the creation of a warm up action for container setup
- Explain and document how it expected to be used

**Comment by lupesko** [comment]
@ankkhedia you did some research on this, what are the results?

**Comment by ankkhedia** [comment]
I performed experiments to understand if warming up was helping in improving the performance. The results showed that the latencies were nit improved for the requests even after some number of requests had hit the server. So, warming up was actually not showing much improvement. 

Closing the issue.
