### ISSUE TITLE
Refactor docker code

### ISSUE THREAD

**Issue by charlieyou** [awslabs/mxnet-model-server#326]
From https://github.com/awslabs/mxnet-model-server/pull/325:
"Seems weird to run all of this stuff in a script and not how a typical Dockerfile is executed. Here, you have to look at two different files to see what's going on (install.sh and the dockerfile).
Each apt-get install or other command can be on a RUN line. Then you can cleanup/optimize how docker handles the commands, taking advantage of caching and layers as needed.
I found this best practices guide helpful." - @aaronmarkham

**Comment by lupesko** [comment]
@vdantu - FYI

**Comment by vdantu** [comment]
I will look into this

**Comment by vdantu** [comment]
Resolved this with my latest commit
