### ISSUE TITLE
GPU Docker build should be changed to use mxnet-cu91mkl

### ISSUE THREAD

**Issue by vdantu** [awslabs/mxnet-model-server#335]
Update the GPU docker file to use mxnet-cu91mkl . Also modify the from image to nvidia/cuda 9.1 cudnn. 

This should be committted if the benchmark shows a hike in performance from current cuda 9.0 in the Dockerfile.

**Comment by ankkhedia** [comment]
@vdantu Can we close this issue. Mkl is in docker file now or do we need something more?

**Comment by vdantu** [comment]
This task is created to move to cu91mkl. We currently have cu90mkl.

**Comment by lupesko** [comment]
Are we planning to do this for the 0.3 release?

**Comment by vdantu** [comment]
We use cu92 image. This can be resolved
