### ISSUE TITLE
Do not allow multiple runs of MMS on a single instance

### ISSUE THREAD

**Issue by vdantu** [awslabs/mxnet-model-server#337]
To manage the host-resources and keep the MMS instances updated with latest models set, there is a need to prevent multiple runs of MMS command. 

The suggestion is that if there exists a previous run of this command running on the host, avoid starting another instance of MMS on the same host. Instead throw an error back saying "There already exists one instance of running MMS"

**Comment by vdantu** [comment]
This has been addressed in the latest version of MMS.

**Comment by vrakesh** [comment]
Resolved in pull request #367
