### ISSUE TITLE
consistent use of locations

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#339]
I see two primary inconsistencies now:
1. `localhost` vs 127.0.0.1
2. model file location

## Default server address
* Change all references of localhost to 127.0.0.1
    - docker instructions and nginx config use localhost, but example inference calls from the zoo use the IP. nginx won't respect the alias. (or make sure nginx does respect the alias)

## Default model location
* Intro tutorials use the auto download from s3 to the current working directory. Later examples expect models in a model folder. 
    - Why not default to a models directory for all examples/tutorials? This way any transition from basic use to docker/prod use is smooth.
    - Can this happen by default so when installing mms it makes a home for models, and the auto-download feature uses this?

**Comment by vdantu** [comment]
I think this is addressed. I will close this issue.
