### ISSUE TITLE
CPU docker image not working

### ISSUE THREAD

**Issue by ThomasDelteil** [awslabs/mxnet-model-server#342]
The wsgi.py file expect `ArgParser.extract_args`
In the latest docker image, the installed version of mms ArgParser class does not have this static method

**Comment by vdantu** [comment]
We had pushed the code changes for model server before pushing out the required pip package. So it was broken for a small duration. It should be fixed now. 
1. Are you working with the docker image on docker hub?
-- This should be working
2. Are you building your own image? 
-- You would need to update the "mxnet-model-server" in the pip installs to "mxnet-model-server==0.3.0b1" before you build your docker image.

**Comment by ThomasDelteil** [comment]
Thanks, just tried the :latest tag that was pushed two hours ago and it worked, good timing!
