### ISSUE TITLE
Few Mxnet models failing

### ISSUE THREAD

**Issue by ankkhedia** [awslabs/mxnet-model-server#345]
Some mxnet models from mms model zoo are failing with mms. The models are lstm_pb and  resnet50_ssd_model.

**Comment by samirbajaj** [comment]
The LSTM model is failing with this error:
`
[ERROR .../mxnet-model-server/mms/serving_frontend.py:predict_callback:472] Traceback (most recent call last):
      File ".../mxnet-model-server/mms/serving_frontend.py", line 468, in predict_callback
        response = modelservice.inference(input_data)
      File ".../mxnet-model-server/mms/model_service/model_service.py", line 101, in inference
        if self.model_name + '_LatencyPreprocess' in MetricsManager.metrics:
    AttributeError: 'MXNetLSTMService' object has no attribute 'model_name'
`

**Comment by vdantu** [comment]
We are looking into this.

**Comment by ankkhedia** [comment]
@samirbajaj 
There is a problem with custom service file provided with the model in our model zoo. I have the fix and once I update model zoo, the error should be gone. Thanks for letting us know of the issue. Please let us know if yo find any other issue.

**Comment by ankkhedia** [comment]
@samirbajaj Updated the model zoo and seems to work fine now.  Also, resnet_50_ssd_model is working fine now. So, closing the issue . Please feel free to reopen the issue or open a new one in case you find any errors.
