### ISSUE TITLE
Explain the parameters needed for fine-tuning performance

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#350]
[This section](https://github.com/awslabs/mxnet-model-server/blob/master/docker/README.md#advanced-settings) details the config params.
It needs to explicitly call out how to tune parameters based on the runtime hardware available, and explain why/how we suggest updating the number of workers.

**Comment by ankkhedia** [comment]
@lupesko I have added the docs about detailed configurations

**Comment by lupesko** [comment]
Thanks @vdantu - closing.
