### ISSUE TITLE
Auto detect number of CPUs for docker config

### ISSUE THREAD

**Issue by ankkhedia** [awslabs/mxnet-model-server#360]
It would be great to detect number of CPUs on your system and use that in docker config instead of user defining it after checking it number of virtual CPUs in their system.

A way to get number of CPUs in Ubuntu
https://askubuntu.com/questions/724228/how-to-find-the-number-of-cpu-cores-including-virtual/724236

**Comment by vrakesh** [comment]
Resolved in pull request #370
