### ISSUE TITLE
Update the mxnet pip package

### ISSUE THREAD

**Issue by vdantu** [awslabs/mxnet-model-server#362]
There might be a need for two pip packages
1. CPU pip package which installs mxnet-mkl
2. GPU pip package which installs mxnet-cu90mkl

**Comment by vrakesh** [comment]
Researched on this

Two possible approaches
1. using PIP --install-option flag - This approach currently fails at PIP level and works at setup.py level. Investigating the reason for failure.

2. Using nvidia-smi via sub-process - This approach will work . But will have to adapt to change in behavior of the tool over time , does it work even if GPU is removed physically, is a question we need to answer.

Right now the manual work around for this issue, while using gpu acceleration, one needs to

`pip uninstall mxnet-mkl`
`pip install mxnet-cu90mkl'

**Comment by lupesko** [comment]
Can't we just use mxnet-cu90mkl since it supports both CPU and GPU?

**Comment by vrakesh** [comment]
Tested out the mxnet-cu90mkl package , it works under Linux for both cpu and gpu.
But Mac and Windows are not supported by the cu90 package as of now

**Comment by vrakesh** [comment]
fixed in pull request #366
