### ISSUE TITLE
Update MMS pip package dependency on MXNet to 1.2.0

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#365]
MXNet is about to release v 1.2.0 in a few weeks.
This issue is suggesting to:
- Update MMS PIP dependency on MXNet to be >= 1.2.0
- Remove onnx-mxnet dependency and replace with the MXNet 1.2.0 contrib ONXN API

The remaining issues originally asked for are handled by #362 - no need to follow up on 
2. Update MMS PIP dependency on MXNet to be for mxnet-mkl
3. Add a new MMS PIP package for gpu: mxnet-model-server-gpu to be for mxnet-cu90mkl
4. Update MMS docker GPU image to depend on mxnet-model-server-gpu
    (and then remove the need to manually remove mxnet and install mxnet-cu90)

@vrakesh @vdantu @ankkhedia - thoughts?

**Comment by vdantu** [comment]
@vrakesh : We should note the EOL of onnx-mxnet and remove that dependency after mxnet 1.2 release.

**Comment by lupesko** [comment]
@vrakesh thanks for clarifying - sounds good.
Let's make sure to test well that cu90mkl works on all supported Linux distributions... you can also check in with the mxnet repo to make sure. The fact that it doesn't work on OSX makes me concerned that it will not work on all Linux distributions...

**Comment by lupesko** [comment]
This should be a blocker for v0.4 release

**Comment by vrakesh** [comment]
resolved in PR #394
