### ISSUE TITLE
[Question] How to handle http return code / exceptions

### ISSUE THREAD

**Issue by ThomasDelteil** [awslabs/mxnet-model-server#385]
I am checking for the dimension of the sent images to make sure they are neither too big nor too small. What sort of exception should I raise in order for it to be gracefully handled by MMS and returned to my user ?

**Comment by lupesko** [comment]
@ThomasDelteil for this and future questions, please submit them at discuss.mxnet.io so other people can learn from the answers.

**Comment by ThomasDelteil** [comment]
Sure, added the question here: https://discuss.mxnet.io/t/handling-of-exceptions-and-https-return-code-in-mms/1048

**Comment by frankfliu** [comment]
This issue will be addressed in MMS 1.1 release.
1.1 release will support full HTTP headers and response handling in service code.
