### ISSUE TITLE
Misleading logging when starting with nginx in Docker container

### ISSUE THREAD

**Issue by ThomasDelteil** [awslabs/mxnet-model-server#388]
When starting with nginx on port 4444 I still get the log:
```
Service health endpoint: 127.0.0.1:8080/ping
```

It would be nice if that matched the nginx port

**Comment by lupesko** [comment]
I understand why you consider this confusing, but NGINX port is external to the local app port.
The app is indeed listening on localhost 8080. NGINX is listening on another port. And the container host may be listening on yet another port...

Any ideas/suggestions/thoughts @frankfliu @vdantu @ankkhedia @vrakesh ?

**Comment by ThomasDelteil** [comment]
Yes I agree with you. What I mean more is maybe more adding some specific logging regarding the nginx port etc. I think most users might not be familiar with the nginx gunicorn flask pre-fork model, so some logging around that would be helpful I think.

**Comment by vrakesh** [comment]
we could ask the Flask app to check if it is running under nginx and accordingly log the information, reading the nginx.conf file??

**Comment by frankfliu** [comment]
Fixed in MMS 1.0 release.
