### ISSUE TITLE
PyPi package lacks Author and Author-email fields, looks bad when you do a pip show

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#398]
PyPi package lacks Author and Author-email fields, looks bad when you do a pip show, looks like:
`
Author: UNKNOWN   
Author-email: UNKNOWN
`

Proposed solution: get Amazon Open Source team recommendation for Author and Email and update setup.py accordingly.

**Comment by lupesko** [comment]
@hyandell would be great to get your suggestion for Author and Author-email for the PyPi package.

**Comment by frankfliu** [comment]
Fixed: https://github.com/awslabs/mxnet-model-server/pull/632
