### ISSUE TITLE
Add Crepe model to MMS model zoo

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#399]
We should add the Crepe Gluon model to the MXNet Model Server model zoo (product classification with CNN), implementation [here](https://github.com/ThomasDelteil/CNN_NLP_MXNet/tree/master/model).

**Comment by vdantu** [comment]
Added this model to the model zoo https://github.com/awslabs/mxnet-model-server/pull/641

**Comment by vdantu** [comment]
Merged the PR
