### ISSUE TITLE
Alexnet inference error

### ISSUE THREAD

**Issue by abhinavs95** [awslabs/mxnet-model-server#400]
After running Alexnet server when I make inference on a test image gives me the following error:
```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>This end point is expecting a data_name of input_0. End point details can be found here:http://&lt;host&gt;:&lt;port&gt;/api-description</p>
```

**Comment by ankkhedia** [comment]
Its a. known thing. when you try to run inference on ONNX model you require to send your request as input_0=data.jpg while when you run it on Mxnet model , it should be data=data.jpg
and that is what the error message shows. It is similar to the already raised issue #277. Marking this as duplicate and closing it.
