### ISSUE TITLE
Wrong Documentation in SSD Example

### ISSUE THREAD

**Issue by anirudhacharya** [awslabs/mxnet-model-server#401]
In the SSD example while launching the model server for inference - 
https://github.com/awslabs/mxnet-model-server/tree/master/examples/ssd#step-6---start-the-inference-service

we run the following command - 
``mxnet-model-server --models SSD=resnet50_ssd_model.model --service ssd_service.py``

the ``SSD`` in the command should be lower case, else while running inference it will result in HTTP 404.

**Comment by vrakesh** [comment]
fixed in PR #407
