### ISSUE TITLE
Gluon example link to AlexNet code is broken

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#402]
Gluon example link is broken:
- "For an actual code implementation, refer to the custom-service code which uses the pre-trained Alexnet"
- Copy the example code and other required artifacts to this folder
[Page and section](https://github.com/awslabs/mxnet-model-server/tree/master/examples/gluon_alexnet#load-and-serve-a-pre-trained-gluon-model).

**Comment by vrakesh** [comment]
fixed in #408
