### ISSUE TITLE
Serving a pretrained Gluon model example does not include all artifacts 

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#403]
Example: https://github.com/awslabs/mxnet-model-server/tree/master/examples/gluon_alexnet#serve-pre-trained-model-with-mms

The sentence "Copy the example code and other required artifacts to this folder" refers to synset.txt, signature.json which are not provided with the example. How are new users following the example supposed to follow it?

Let's make it simpler and add links to every file needed, plus the curl commands to download.

**Comment by frankfliu** [comment]
Fixed in MMS 1.0
