### ISSUE TITLE
Gluon pre-trained example service code is missing import statements

### ISSUE THREAD

**Issue by lupesko** [awslabs/mxnet-model-server#405]
Gluon pre-trained [example service code](https://github.com/awslabs/mxnet-model-server/tree/master/examples/gluon_alexnet#load-and-serve-a-pre-trained-gluon-model) is missing import statements

Import statements missing:
```
import mxnet
from mms.model_service.gluon_vision_service import GluonVisionService
```

**Comment by lupesko** [comment]
@vrakesh wanted to make sure this is on your radar.

**Comment by vrakesh** [comment]
@lupesko sure will created PR #421 for this

**Comment by lupesko** [comment]
Thanks. Merged.

**Comment by vrakesh** [comment]
resloved in PR #421
