### ISSUE TITLE
shufflenet integration test temporarily removed

### ISSUE THREAD

**Issue by vrakesh** [awslabs/mxnet-model-server#411]
With mxnet-mkl 1.2 , shufflenet runs into the following problem

 raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:05:45] src/operator/tensor/../tensor/elemwise_unary_op.h:301: Check failed: inputs[0].dptr_ == outputs[0].dptr_ (0x7fa99f41b000 vs. 0x7fa99f435200) 

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010fef8684 libmxnet.so + 26244
[bt] (1) 1   libmxnet.so                         0x000000010fef843f libmxnet.so + 25663
[bt] (2) 2   libmxnet.so                         0x0000000110316021 libmxnet.so + 4341793
[bt] (3) 3   libmxnet.so                         0x0000000110ff4993 MXNDListFree + 139843
[bt] (4) 4   libmxnet.so                         0x0000000111015705 MXNDListFree + 274357
[bt] (5) 5   libmxnet.so                         0x0000000110fe526c MXNDListFree + 76572
[bt] (6) 6   libmxnet.so                         0x0000000110fe7fe1 MXNDListFree + 88209
[bt] (7) 7   libmxnet.so                         0x0000000110fe7ef7 MXNDListFree + 87975
[bt] (8) 8   libmxnet.so                         0x0000000110fe5fe5 MXNDListFree + 80021
[bt] (9) 9   libsystem_pthread.dylib             0x00007fffa9e2a93b _pthread_body + 180

This issue has been reported to the mxnet team, shufflenet will not be run as part of integration test until this is fixed

**Comment by vrakesh** [comment]
related mxnet issue
https://github.com/apache/incubator-mxnet/issues/11028

**Comment by vdantu** [comment]
Seems like the mxnet PR is merged. We should remove this from on hold

**Comment by vrakesh** [comment]
This is should re-enabled when we move our dependency to mxnet 1.3 from 1.2, the fix is the master branch of mxnet

**Comment by vrakesh** [comment]
In MMS 1.0 the integration tests have changed, however added back shufflenet to model zoo via PR #747 

So resolving this issue
