### ISSUE TITLE
improve onnx export methodology

### ISSUE THREAD

**Issue by vrakesh** [awslabs/mxnet-model-server#413]
with mxnet 1.2 we no longer use onnx_mxnet but ,mxnet.contrib.onnx.

This involves changes . to input layer nomenclature, we need to identify this by reading the model and updating signature json, rather for onnx should we generate signature.json file?

**Comment by vdantu** [comment]
1. In model-archiver 1.0, we update the signature file's (for onnx models) input shapes from the onnx model file. 
2. The model-archiver *doesn't* depend on onnx_mxnet package but relies on mxnet.contrib.onnx and we also rely on the latest mxnet (1.3.0). 

I think we can close this issue. Please re-open this, if you feel there are any concerns with this justification.
