### ISSUE TITLE
Understand why post process step has some latency, despite most work happening in inference.

### ISSUE THREAD

**Issue by vrakesh** [awslabs/mxnet-model-server#416]
With squeezent, on a single request the latency by just doing a topk computation is 
about 5ms

Without the topk run (returning a generic dictionary) the latency is down to 0.09ms

We need to understand how to improve the topk prediction part of post process

**Comment by vdantu** [comment]
Is this because of lazy evaluation??

**Comment by frankfliu** [comment]
dup of: https://github.com/awslabs/mxnet-model-server/issues/289
