### ISSUE TITLE
Export ignores folders

### ISSUE THREAD

**Issue by abhinavs95** [awslabs/mxnet-model-server#424]
I am trying to export an mxnet model to mms archive:

`mxnet-model-export --model-name r100 --model-path .`

The folder contains the all the items required for export (symbols, params, signature, synset, etc.) along with another folder "mtcnn-detector" containing preprocessing code.

The export module ignores the folder "mtcnn-detector" and only wraps up the rest of the items in the .model archive which leads to error during inference.

**Comment by vrakesh** [comment]
Will look into this

**Comment by lupesko** [comment]
Could be that the export utility does not pack up nested directories.
@abhinavs95 as a workaround until this is fixed, you can have all of the python code in a single file and use it from there.

**Comment by abhinavs95** [comment]
Actually the inner folder contains pre-trained symbols and params of a face detection model which is used for pre-processing in my model. When I dump all the files into one folder, the export throws an error due to the presence of multiple params and symbol files.

As a workaround I hardcoded the manifest file and packaged the archive using zip, which seems to work fine.

**Comment by vrakesh** [comment]
@lupesko yes there is a fix for this, I will check it in with a unit test tomorrow.

**Comment by vrakesh** [comment]
Fixed in PR #426
