### ISSUE TITLE
Confusing warning message about a WSGI server

### ISSUE THREAD

**Issue by aaronmarkham** [awslabs/mxnet-model-server#445]
I saw the following warning message after starting a server. It is telling me I'm in "production" then says not to use the development server in production. I guess I must be using the "development server". Which is bad? Ok, so then it says use a "WSGI server". I searched the MMS repo for "WSGI" and only see code mentions around docker. No docs... I think you mean that I should be looking at the Docker implementation of MMS for production. How do you decide if I'm in production or development? Anyways, this messaging could be improved. Let me know the real intent and I can help out with that.

```
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
```

**Comment by lupesko** [comment]
Since Flask is going away, won't it be resolved anyway?

**Comment by vdantu** [comment]
Yes, that should fix the warning/logs. :)

**Comment by frankfliu** [comment]
This issue is no longer relevant in MMS 1.0.
