### ISSUE TITLE
Wrong entry point for MMS on Fargate

### ISSUE THREAD

**Issue by codewithsk** [awslabs/mxnet-model-server#481]
I'm unable to successfully start tasks using the default MMS container entry point as explained in the [MMS on Fargate tutorial](https://github.com/awslabs/mxnet-model-server/blob/master/docs/mms_on_fargate.md). I get the following error:

```bash
CannotStartContainerError: API error (400): OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"mxnet-model-server.sh\": executable file not found in $PATH":
```

**Comment by vdantu** [comment]
@codewithsk : Closing this as the PR was merged..
