### ISSUE TITLE
why revert the batching relevant components?

### ISSUE THREAD

**Issue by HaoLiuHust** [awslabs/mxnet-model-server#483]
Is there any issue?

**Comment by vdantu** [comment]
@HaoLiuHust : Which batching components are you referring to? Would like to understand the question a little better.

**Comment by HaoLiuHust** [comment]
@vdantu do you have some advice?

**Comment by vdantu** [comment]
@HaoLiuHust : That branch was experimental. There is ongoing work on making those changes more streamlined. With current release (0.4), the requests are processed one after another.

**Comment by HaoLiuHust** [comment]
I see, hope for the changes

**Comment by lupesko** [comment]
Closing the issue, @HaoLiuHust stay tuned for MMS 1.0!
