### ISSUE TITLE
Docker version control

### ISSUE THREAD

**Issue by codewithsk** [awslabs/mxnet-model-server#487]
Currently, pulling the MMS docker container from Dockerhub contains a container with the latest release of MMS (through pip install). However, this will affect backward compatibility of currently deployed models in future releases. There must be a way to pull a different version of the container. Moreover, currently, if the container build on Dockerhub fails, there is no way to roll back to a previous build on Dockerhub. It would be helpful if the docker images were tagged with a version number and the latest tag always points to the latest version.

**Comment by vdantu** [comment]
@codewithsk: We have a 0.4 release for MMS on dockerhub already. This is built when the release was cut. Wouldn't this be sufficient?

**Comment by vdantu** [comment]
We have a new set of released docker images on docker hub at 

https://hub.docker.com/r/awsdeeplearningteam/mxnet-model-server/ 

If there are any concerns, please feel free to reopen this issue.
