### ISSUE TITLE
arcface service produce wrong result

### ISSUE THREAD

**Issue by photoszzt** [awslabs/mxnet-model-server#651]
I try the arcface onnx model by download the mar package. But the output seems wrong. 

With the image given, the output I get is
{
    "Distance": 0.0,
    "Similarity": 1.0
}

But if I download the onnx model from https://github.com/onnx/models/tree/master/models/face_recognition/ArcFace, the output I get is 
Distance = 0.461761                                                                                                                                                                                                
Similarity = 0.769120

The model in the mar package is correct. I unzip the mar and load the resnet100-0000.params and symbol.json. I get the same output. 

I think there's something wrong with the inference code either in arcface_service.py or the template file. I replace the template file with the most recent one but still no difference.

**Comment by vdantu** [comment]
Thanks for lodging the issues. I will take a look and get back.

**Comment by frankfliu** [comment]
@photoszzt, This is a bug in arcface_service.py code. We should deepcopy each forward result for each image.

.mar file is updated. Please try it again.
new arcface_service.py can be found: https://s3.amazonaws.com/model-server/model_archive_1.0/examples/onnx-arcface-resnet100/arcface_service.py
