### ISSUE TITLE
Broken docs

### ISSUE THREAD

**Issue by sandeep-krishnamurthy** [awslabs/mxnet-model-server#673]
Note: The model name can be override when register model with [Register Model API](../ docs/management_api.md#register-a-model).

Here - https://github.com/awslabs/mxnet-model-server/blob/master/model-archiver/README.md#model-name

**Comment by sandeep-krishnamurthy** [comment]
https://github.com/awslabs/mxnet-model-server/blob/master/model-archiver/README.md#excluded-files

Follow type of file -> Following types of files

**Comment by sandeep-krishnamurthy** [comment]
https://github.com/awslabs/mxnet-model-server/blob/master/model-archiver/README.md#handler

to executes inference code => to execute inference code

**Comment by zachgk** [comment]
Thanks for the help cleaning up our docs @sandeep-krishnamurthy. I went over the file in question and fixed those problems (among others) in #674

**Comment by vdantu** [comment]
@zachgk : Were all the comments addressed by your PR?

**Comment by zachgk** [comment]
Yes, I addressed all the comments above. I will close the issue for now. If there are more suggestions, please reopen this or create a new issue/PR with those suggestions.

**Comment by vdantu** [comment]
I think we had missed one of the comments, I raised a PR and tagged that to this issue.
