### ISSUE TITLE
broken link in fargate doc

### ISSUE THREAD

**Issue by srochel** [awslabs/mxnet-model-server#693]
https://github.com/awslabs/mxnet-model-server/blob/master/docs/mms_on_fargate.md 
See: 
With the current release of MMS, 1.0, Official pre-configured, optimized container images of MMS are provided on Docker hub.

awsdeeplearningteam/mxnet-model-server:1.0.0-mxnet-cpu

Link to awsdeeplearningteam/mxnet-model-server:1.0.0-mxnet-cpu is creating 404

**Comment by frankfliu** [comment]
Thanks for reporting this issue. We will fix the broken link.

**Comment by frankfliu** [comment]
This is fixed.
