### ISSUE TITLE
use MMS in SageMaker

### ISSUE THREAD

**Issue by photoszzt** [awslabs/mxnet-model-server#698]
Can I use mxnet model server in SageMaker? I can deploy my own container in SageMaker.  I read the examples provided in SageMaker and don't find any documentation related to that.

**Comment by photoszzt** [comment]
The reason I want to use SageMaker is they provide GPU access while Fargate doesn't.

**Comment by vdantu** [comment]
@photoszzt : Yes, you can use MMS in Sagemaker. As of today, you could use MMS as a "bring your own" container solution in Sagemaker. You can find examples of how "bring your own" works [here]( https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality). The steps you need to follow are as follows:
1. Follow instructions [here](https://github.com/awslabs/mxnet-model-server/blob/master/model-archiver/README.md) to create a .mar file.
2. Use "tar" to create a .tar.gz file from the .mar file. Eg. If you have a my_model.mar file, run ```tar zcvf my_model.tar.gz my_model.mar```
3. Upload this to S3 bucket.
4. Build your container with MMS and other packages that you depend on.
5. Follow Sagemaker instructions to create endpoint configuration and endpoint. 

This should work.

**Comment by vdantu** [comment]
@photoszzt : Also, please let us know if you find any issues with using MMS.

**Comment by photoszzt** [comment]
@vdantu thanks for the reply. Previously I setup the SageMaker following the link you provided. I will follow your steps to see whether it works or not.

**Comment by lupesko** [comment]
@photoszzt why not just run MMS on an ec2 instance or ECS (ECS does support GPU)?

**Comment by photoszzt** [comment]
@lupesko I'm new to AWS service. I'm open to any suggestion. I actually start from AWS Lambda but it's too limited on CPU power and package size. I want something that can manage my container with GPU access and billed by per second or even smaller, not by hour. I think ECS doesn't support GPU? I check the configure page and I don't find a place to add GPU to it. Maybe I'm missing something?

**Comment by lupesko** [comment]
@photoszzt you can certainly use GPU in ECS, here is an example: https://aws.amazon.com/blogs/compute/orchestrating-gpu-accelerated-workloads-on-amazon-ecs/
You can also just run MMS on EC2 using a GPU instance such as P3.

I'm curious to understand your company use case, feel free to shoot me an email to lupesko@gmail.com

**Comment by vdantu** [comment]
@photoszzt : As @lupesko suggested, you could create a service on ECS as EC2 hosted service (instead of Fargate). Its almost the same steps except at the beginning you would need to [choose EC2](https://camo.githubusercontent.com/24a983410e48087d5e186d6d83d86bd245ff4847/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6d6d732d6769746875622d6173736574732f4d4d532b776974682b466172676174652b41727469636c652f325f53656c6563745f466172676174652e706e67) instead of Fargate :). EC2 does have GPU support, you could choose from multiple GPU instances. Do let us know if you have any questions or face any difficulties.

**Comment by vdantu** [comment]
@photoszzt : Were you able to start your service on ECS Fargate/EC2 service? If you have trouble, you could join the slack channel set up. You can get real-time help with setting it up.

**Comment by photoszzt** [comment]
@vdantu I'm traveling recently so I don't have a chance to test them yet but I will try the slack channel if I have any question. By the way, what's the slack channel link?

**Comment by vdantu** [comment]
@photoszzt : This is the link to our [Slack Channel](https://join.slack.com/t/mms-awslabs/shared_invite/enQtNDk4MTgzNDc5NzE4LTBkYTAwMjBjMTVmZTdkODRmYTZkNjdjZGYxZDI0ODhiZDdlM2Y0ZGJiZTczMGY3Njc4MmM3OTQ0OWI2ZDMyNGQ).

**Comment by vdantu** [comment]
@photoszzt : Just checking in. Hows the deployment coming along? Were you able to lauch your service using Amazon ECS (EC2) ?

**Comment by ddavydenko** [comment]
Closing this issue, as suggestions are provided and [slack channel](https://join.slack.com/t/mms-awslabs/shared_invite/enQtNDk4MTgzNDc5NzE4LTBkYTAwMjBjMTVmZTdkODRmYTZkNjdjZGYxZDI0ODhiZDdlM2Y0ZGJiZTczMGY3Njc4MmM3OTQ0OWI2ZDMyNGQ) proposed for following up. Please feel free to reopen this issue in case you have additional questions.
