### ISSUE TITLE
Error: Unable to access jarfile

### ISSUE THREAD

**Issue by lxy5513** [awslabs/mxnet-model-server#716]
Hi 
After Prerequisites and installed relevant packages, I run this quick start, but some error occured, as follow: 
$ mxnet-model-server --start --models squeezenet=https://s3.amazonaws.com/model-server/model_archive_1.0/squeezenet_v1.1.mar
Error: Unable to access jarfile /Users/liuxingyu/experiments/mxnet-model-server/mms/frontend/model-server.jar

![image](https://user-images.githubusercontent.com/39720528/50431020-9079d980-0902-11e9-8039-590e0e8eaf89.png)

**Comment by vdantu** [comment]
@lxy5513 
Could you please let us know the following.
1. What step did you follow to install mxnet-model-server? It appears that you used "pip install -U -e . ". If that is the case, you would need to run ```python setup.py build``` from "mxnet-model-server" directory, before running ```pip install -U -e . ```
2. What is the OS?
3. Are you using any python virtualenv or conda environment?
4. Could you paste the output of "pip list"?
5. Could you paste your PYTHONPATH environment variable? (echo $PYTHONPATH)

**Comment by vdantu** [comment]
I would recommend running ``` pip install -U mxnet-model-server``` . You don't need to install from source. It is currently distributed through PyPi.

**Comment by lxy5513** [comment]
first of all, Thanks for your reply! 
After run `python setup.py build`, It still had same error   
my OS is Ubuntu 16.04   
my use virtualenvwrapper  
pip list as follow: 
> Package            Version 
backcall           0.1.0
cairocffi          0.9.0
CairoSVG           2.2.1
certifi            2018.11.29
cffi               1.11.5
chardet            3.0.4
Click              7.0
cssselect2         0.2.1
cycler             0.10.0
decorator          4.3.0
defusedxml         0.5.0
enum-compat        0.0.2
future             0.17.1
graphviz           0.8.4
idna               2.8
ipdb               0.11
ipython            7.2.0
ipython-genutils   0.2.0
jedi               0.13.1
kiwisolver         1.0.1
matplotlib         3.0.2
model-archiver     1.0.1
mxnet-cu92mkl      1.3.1
mxnet-mkl          1.3.1
mxnet-model-server 1.0.1
numpy              1.14.6
parso              0.3.1
pbr                5.1.1
pexpect            4.6.0
pickleshare        0.7.5
Pillow             5.3.0
pip                18.1
progress           1.4
prompt-toolkit     2.0.7
psutil             5.4.8
ptyprocess         0.6.0
pycparser          2.19
Pygments           2.3.0
pyparsing          2.2.2
python-dateutil    2.7.5
requests           2.21.0
scipy              1.1.0
setuptools         40.6.3
six                1.11.0
stevedore          1.29.0
svgwrite           1.1.12
tinycss2           0.6.1
tiv                0.2.0
torch              0.4.0
torchvision        0.2.1
traitlets          4.3.2
Tree               0.2.4
urllib3            1.24.1
virtualenv         16.0.0
virtualenv-clone   0.4.0
virtualenvwrapper  4.8.2
wcwidth            0.1.7
webencodings       0.5.1
wheel              0.32.3 . 


python -V  
> Python 3.5.2 
( I tried python3.6, it is still wrong)

however I use docker, It's OK, I can build my own special mxnet-model-server (python version is 2.7), So, is it owing to the python version?

**Comment by vdantu** [comment]
could you uninstall and reinstall mxnet-model server? 

```pip uninstall -y mxnet-model-server```
and then run
```pip install mxnet-model-server```

Something is wrong in the error message. Usually, the ```pip install`` packages go into site-packages or dist-packages. In your case, the error points to a local mxnet-model-server repository, which suggested that you installed the package from local repository. But, your ```pip list``` shows that you have mxnet-model-server versions 1.0.1 so its probably not picking from local repository. 

Could you run one more debug:

Run ```python`` on your terminal

```
$ python
>>> import os
>>> os.__file__
<Copy-Paste the file path here>
```

**Comment by lxy5513** [comment]
Thanks for your advice,
I use virtualenvwrapper which site-packages inherits python3.5 packages 
```mkvirtualenv -p /home/xyliu/PATH/python-3.5.2/python3/bin/python3 --system-site-packages mms```  

packages site is :   
> /home/xyliu/PATH/python-3.5.2/python3/lib/python3.5/site-packages 

virtualenv packages is: 
> /home/xyliu/.virtualenvs/mms/lib/python3.5/site-packages/ 

```
$ python
>>> import os
>>> os.__file__
>>> '/home/xyliu/PATH/python-3.5.2/python3/lib/python3.5/os.py'
```

 I uninstall and reinstall mxnet-model server and error same     
sad...

**Comment by vdantu** [comment]
Could you run ```pip uninstall -y mxnet-model-server``` from inside your virtual environment and then run ```pip install -IU mxnet-model-server```. The ```-I``` is a substitute for ```--ignore-installed```. Once this is done, could you paste the output of ```which mxnet-model-server```.

The base issue seems to be that you have a version of "mxnet-model-server" installed globally and the virtual environment seems to be using that.  To verify this you could run ```which mxnet-model-server```. If this points to your global site-packages, I would recommend you deactivating your virtual environment and running ```pip uninstall -y mxnet-model-server ``` at the global level.

**Comment by lxy5513** [comment]
OK, these are terminal command
![image](https://user-images.githubusercontent.com/39720528/50468047-e2912c80-09e0-11e9-8721-f87dc8ca9ef1.png)

After I pip install -IU mxnet-model-server, it occurs some warnings:
![image](https://user-images.githubusercontent.com/39720528/50468105-1ec48d00-09e1-11e9-9b41-d3b47baa6f57.png)

Then ``which mxnet-model-server```
> /home/xyliu/.virtualenvs/mms/bin/mxnet-model-server   

It should install in virtualenvs packages

**Comment by lxy5513** [comment]
Should I install numpy and Pillow of special vision in my virtualenv packages? 

![image](https://user-images.githubusercontent.com/39720528/50468289-f8532180-09e1-11e9-86a8-c27f83a65904.png)

**Comment by vdantu** [comment]
Ya. Your installation wasn't successful. The simplest solution is to create a new and clean virtual environment. Also, I would recommend not using the ```--system-site-packages``` option in the creation of the virtual environment.

**Comment by vdantu** [comment]
@lxy5513 : Did clean installation resolve your issue? If yes, could we close this issue?

**Comment by vdantu** [comment]
I would suggest we try a little more to fix it, but its upto your discretion:
Step 1: You could **go out of your current virtualenv** and remove mxnet-model-server from global location there by running ```pip uninstall mxnet-model-server```. In the same place do ```pip install -U numpy Pillow```.
Step 2: We commonly use virtualenv (not wrapper). You could try using just the virtualenv to create a new environment. For example ```virtualenv -p /usr/local/bin/python3.6 my_py3_environment``` and then activate it ```source my_py3_environment/bin/activate```. This should create a clean virtual environment where you could use ```pip install mxnet-model-server```.
Step 3: Delete all other virtual environments that are not under use.

**Comment by lxy5513** [comment]
Ok thanks，today is too late(my computer is in company) . 
Tomorrow morning I will try it according to your advice

**Comment by lxy5513** [comment]
I found a very weird thing, In the repository, It occurs error
![image](https://user-images.githubusercontent.com/39720528/50534034-2dda4500-0b71-11e9-95f8-df94d961cbee.png)

However in other repository, it works normally, through on former virtaulenv(use the --system-site-packages option )

**Comment by vdantu** [comment]
Sorry, I couldn't follow your comment. Could you elaborate a little. What error has occurred in the repository? I only see a list of files in mxnet-model-server directory, in your screen shot.

Also, you wouldn't need a clone of the repository to run the model-server. ```pip install -U mxnet-model-server``` installs all the required code.

**Comment by lxy5513** [comment]
Sorry，the error is that I mentioned at first. 
Error: Unable to access jarfile /Users/liuxingyu/experiments/mxnet-model-server/mms/frontend/model-server.jar

**Comment by vdantu** [comment]
So what you are saying is, with this repository you are facing the issue? As I had mentioned, you don't need a have a clone of the repository to run mxnet-model-server. 
Did you try to remove the installed "mxnet-model-server" from the **global site-packages**?  Your package is referencing a non site-package location, which is wrong. Could you do the following,
1. Remove mxnet-model-server from global site-packages
2. Remove mxnet-model-server from the virtual environment
3. Look at ```pip list``` and verify that there is no "mxnet-model-server"
4. Install mxnet-model-server in the virtual environment.
5. Run ```history``` and send across the list of steps you performed.  

Also, would you like to join the slack channel? It might be quicker to debug this on a messenger.

**Comment by lxy5513** [comment]
Yes.  I just feel weird,it doesn't  matter . Thanks for all of yours replies . 
You can close this issue

**Comment by deimsdeutsch** [comment]
I am facing the same issue and its quite recurrent. I think a fix should be made available.
