### ISSUE TITLE
How to debug frontend in idea?

### ISSUE THREAD

**Issue by cqlyiyeshu** [awslabs/mxnet-model-server#717]
Can you tell me  how to debug frontend in idea? when I set the breakpoint in ModelServer's main, and run gradle build, but it can't stop. Then how to debug it?

**Comment by vdantu** [comment]
@cqlyiyeshu : You would have to run model server in your debug config, not gradle build to have breakpoints working. Just curious, what's your use case for debugging the model-server? Are you seeing any issue?

**Comment by cqlyiyeshu** [comment]
Oh, ths for your reply. I just went to test debug server. When I debug the ModelServer, it got the error information: Error:Unable to make the module: server, related gradle configuration was not found. Please, re-import the Gradle project and try again.
Have you got the tutorial? @vdantu

**Comment by vdantu** [comment]
@cqlyiyeshu : We currently don't have a tutorial or doc for this. We will need to work on it.

**Comment by ddavydenko** [comment]
@cqlyiyeshu , I suggest you join MMS Slack [channel](https://join.slack.com/t/mms-awslabs/shared_invite/enQtNDk4MTgzNDc5NzE4LTBkYTAwMjBjMTVmZTdkODRmYTZkNjdjZGYxZDI0ODhiZDdlM2Y0ZGJiZTczMGY3Njc4MmM3OTQ0OWI2ZDMyNGQ) to debug your issue further as using github for debugging session might be challenging.
