### ISSUE TITLE
[Question] How does one adjust payload size limits for POST (e.g maxFileSize / maxRequestSize)?

### ISSUE THREAD

**Issue by fpertl** [awslabs/mxnet-model-server#738]
When POSTing data for inferencing, the data blob in the POST body could become larger than allowed by the server (e.g when batching?!)  Are there configuration options for the server such as maxFileSize / maxRequestSize?

**Comment by vdantu** [comment]
At this time there is no config for this. Are you seeing any issues with
this?

Thanks,
Vamshi

**Comment by fpertl** [comment]
Vamish, thanks for the reply. I was just trying out some inferenceing without paying attention to image size.  When POSTing a png 4096x2160 the server returned a 413.  Scaling the image down prior to POSTing works fine.  I'm still trying to figure stuff out and am not sure how batching works behind the scenes (http requests vs custom model etc.) , but if a batch for a custom model will need to be submitted as a single POST I could see request size becoming an issue for larger batches?! 

``` 
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /predictions/resnet50_ssd_model HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.58.0
> Accept: */*
> Content-Length: 15326901
> Expect: 100-continue
> 
< HTTP/1.1 413 Request Entity Too Large
< content-length: 0
* HTTP error before end of send, stop sending
< 
* Closing connection 0
```

**Comment by vdantu** [comment]
@fpertl 
Actually, the max batch request you can currently capped at 6.25Mb. This could potentially be an issue. We can look into this. Thanks for sharing your urser experience with the error code :)

**Comment by fpertl** [comment]
No problem. Thanks for the awesome project :)  For what its worth, I do think that people looking at model-servers will be interested in inferenceing large amounts of data efficiently (i.e. batch)

**Comment by vdantu** [comment]
The PR has been merged. Please feel free to re-open this issue if this issue still persists.
