### ISSUE TITLE
Configuration max_workers ignored

### ISSUE THREAD

**Issue by ThomasDelteil** [awslabs/mxnet-model-server#751]
This configuration item is simply ignored from `config.properties`

**Comment by vdantu** [comment]
I don't think this is a released parameter yet. Did you use a released version of MMS? We are releasing 1.0.2 next week, this feature will be a part of that release.

**Comment by ThomasDelteil** [comment]
I am using the example config file I found in the documentation

**Comment by vdantu** [comment]
Ok. I think this feature will start working if you use prerelease version of MMS package. We will make a release of this early to mid next week.
