### ISSUE TITLE
how to choose gpu in mms.

### ISSUE THREAD

**Issue by JustinhoCHN** [awslabs/mxnet-model-server#754]
In a multi gpu machine (say 4 gpus), mms can only specify the number of gpu, start from gpu 0. But if there're anther service using gpu 0, mms cannot skip the gpu 0. Can we specify gpu in the config.properties file? I've checked the custom service code, we can specify the mms context using which device, but it's not convenient.

**Comment by vdantu** [comment]
Currently MMS only takes a num-GPU as option, and it uses these many number
of GPUs starting from GPU ID 0 . The only way to over ride this is in the
Custom Service Code. Just curious, wouldnt we want to use the whole host to
run inference service? What is the use case where we would want to share
the GPU resources in production setup?

**Comment by frankfliu** [comment]
@JustinhoCHN 
We didn't figure out an intuitive way to assigning GPU for each worker in config.properties. Please share your ideas if you have some suggestion.

In current MMS implementation, you can limit number gpus for your workers. each worker will be assigned a gpu_id. your service code can get assigned gpu_id via context.

In your use case, if you want to skip GPU(0), you can defined a environment variable says:
```
export GPU_ID_OFFSET=1
```

then in your service code:
```
properties = context.system_properties
gpu_id = properties.get("gpu_id")
off_set = int(os.environ['GPU_ID_OFFSET'])
self.mxnet_ctx = mx.cpu() if gpu_id is None else mx.gpu(gpu_id + off_set)
```

**Comment by JustinhoCHN** [comment]
@vdantu actually, our server would serve different kinds of service, such as nlp service, cv service, or even using different deep learning framework, it's a common situation in our company. If someone serves a tensorflow model in gpu 0, as we all know, tensorflow would consume all of memory in gpu 0, so my mms can not use the gpu 0, I don't know if there's insufficient gpu memory, mms would crash or not, so I have to choose another gpu, there's source limitation for different services in our case.

@frankfliu That's a smart implementation, I'll consider it. My suggestion is, in the config.properties, num_of_gpu can take int number or a list that contains gpu numbers as input, when mms parsing the config.properties, 
```
properties = context.system_properties
gpu_id = properties.get("gpu_id")
self.mxnet_ctx = [mx.gpu(x) for x in gpu_id]
```
I don't know if mms can parsing config like this, just guess, but it would be convenient.

**Comment by vdantu** [comment]
True. We will look into adding whitelist option for GPUs used.

**Comment by haoweiliang1996** [comment]
just export CUDA_VISIBLE_DEVICES="1,2,3" then add number_of_gpu=3 to config.properites.

**Comment by JustinhoCHN** [comment]
@haoweiliang1996 nah, it doesn't work.

**Comment by haoweiliang1996** [comment]
@JustinhoCHN It work for me,  CUDA_VISIBLE_DEVICES restrict the devices that your CUDA application sees。In principle it will not be affected by deep learning framework。

**Comment by JustinhoCHN** [comment]
@haoweiliang1996 Have you ran this before creating docker container? I think this host env variable doesn't work for container environment. Just guess.

**Comment by JustinhoCHN** [comment]
I figured it out. If you are using docker container, you should **enter the container bash terminal** (command: ```sudo docker exec -it mms bash```), before starting the mxnet-model-server, ```export CUDA_VISIBLE_DEVICES="2,3"``` or whatever gpu you want, and then start the mms.

**Comment by vdantu** [comment]
@JustinhoCHN : Thanks for following this up :) . This will be a useful feature :)
