### ISSUE TITLE
Custom serving for non-MXNet or ONNX models -- error handling (with status codes, response body)?

### ISSUE THREAD

**Issue by andremoeller** [awslabs/mxnet-model-server#757]
Hi,

My model is neither an MXNet nor ONNX model. I'd like to load the model artifacts, and write custom code to do some preprocessing and to invoke the loaded model. Is there a way to do this with MXNet Model Server?

Also, if I've written my own serving code, how does error handling work? For example: the input payload is bad so my preprocessing fails. How can I respond with a 400 status code and return the right error message in the response payload?

Thanks!

**Comment by vdantu** [comment]
We are in the process of writing a document to bring your own DL framework
to MMS. We will publish this sometime next week. For now, to unblock
yourself, you could follow the custom service code(
https://github.com/awslabs/mxnet-model-server/blob/master/docs/custom_service.md).
This walks over how you could write your own handler/entry point to MMS.

For error handling part,
1. Error that your code handles needs to be bubbled up to the client. For
this you could add a custom error response string and pass it to MMS, it
takes care of forwarding this error response to the clients.
2. Errors that aren't handled by your code. If your code throws an
exception, or if the code doesn't return a proper list of responses , MMS
catches these errors and throws back a 503 error to the clients with a
response string saying "prediction failed".

You could refer to "predict" method in
https://github.com/awslabs/mxnet-model-server/blob/master/mms/service.py
for more info on how errors are handled.

Does this help?

**Comment by vdantu** [comment]
We are in the process of defining interface for returning a specific error code per request in the batch from the custom-service-code. I will tag this as enhancement for that reason.

**Comment by andremoeller** [comment]
OK, thanks, that is helpful. To clarify:

Right now, if I write my own service, I can specify the error response body, but the status code is always 503. MMS is working on a way for me to write my own service, tell MMS I want to respond with a 400 or a 415 or some other status code (along with my custom response body), so I can tell the client to modify their request rather than telling them that the server erred.

Is that right?

And as-is: if I were writing my own service, how would I specify my own error response body? I reread the custom service doc and it doesn't mention this -- could this be added to the custom service doc? Or is it documented elsewhere?

Thanks.

**Comment by vdantu** [comment]
If there is an invalid request, the custom service code can send back
"invalid request" as a response, this will cause a custom error message
sent to the client. But, this will be a 200 http code. But, if you want a
non-200 code, simply throw an exception.  MMS will return a 503, with a
standard error message.

**Comment by frankfliu** [comment]
In our current design, you can report your status code back to client in your service code via:
context.report_status(400, "Invalid input data")

This API is already available service code. Unfortunately, this implementation has not completed yet in our frontend. You still seeing 200 from client side in MMS 1.0

Will update this issue when we implemented this.
