### ISSUE TITLE
An error occurred while using requests and postman requests

### ISSUE THREAD

**Issue by aikudexiaohai** [awslabs/mxnet-model-server#758]
when I use requests code and postman，I can not get any response。how can I use postman to send a image and what is the file's key

**Comment by aikudexiaohai** [comment]
I solved it

**Comment by vdantu** [comment]
@aikudexiaohai : Could you specify what issue you faced and what you did to fix it a little more in detail. It would be helpful for the community, if anyone in the future hits similar issue in the future :) .
