### ISSUE TITLE
A bug occurred while processing an error request

### ISSUE THREAD

**Issue by aikudexiaohai** [awslabs/mxnet-model-server#759]
When I send an erroneous request with python's requests package, I get an error "'NoneType' object is not iterable". But when I send a correct request, I still get this error. So I suspect that the error flag in the service program has not been reset. so I added self.error=None at the beginning of the data receiving function in mxnet_vision_server.py, and the problem disappeared.

**Comment by aikudexiaohai** [comment]
I don't know if this is a bug or my code is wrong.

**Comment by ddavydenko** [comment]
@aikudexiaohai, there is no pertained state between requests in MMS. What would help if you could post some more details about your custom service code so we would be able to take a deeper look.

**Comment by aikudexiaohai** [comment]
class MXNetVisionService(MXNetModelService):

    def preprocess(self, request):

        self.error = None                     # I add this line

        img_list = []
        param_name = self.signature['inputs'][0]['data_name']
        input_shape = self.signature['inputs'][0]['data_shape']

        for idx, data in enumerate(request):
            img = data.get(param_name)
            if img is None:
                img = data.get("body")

            if img is None:
                img = data.get("data")

            if img is None or len(img) == 0:
                self.error = "Empty image input"
                return None

            # We are assuming input shape is NCHW
            [h, w] = input_shape[2:]

            try:
                img_arr = image.read(img)
            except Exception as e:
                logging.warn(e, exc_info=True)
                self.error = "Corrupted image input"
                return None

            img_arr = image.resize(img_arr, w, h)
            img_arr = image.transform_shape(img_arr)
            img_list.append(img_arr)
        return img_list

wrong request code:
data = {'file': open('./images/1.jpg', 'rb')}
res = requests.request('POST', url, files=data)
print(res.text)
this will recieve wrong reponse 'NoneType' object is not iterable because the key value 'file' is wrong, it should be 'data'

correct code:
data = {'data': open('./images/1.jpg', 'rb')}
res = requests.request('POST', url, files=data)
print(res.text)
I use this correct code, still recieve 'NoneType' object is not iterable，but if I add self.error=None，I will recieve correct response

**Comment by aikudexiaohai** [comment]
Is self.error not reset? A wrong request will affect the next correct request

**Comment by vdantu** [comment]
@aikudexiaohai : Thanks for finding this issue and raising it 👍 . The code you are pointing to is custom code which is meant to be modified by customers writing models :) . We would recommend customers modifying this code according to their needs. That said, you have a valid point here. We might need to fix this in our example implementation as well. 

Just out of curiosity, are you using one of the models from MMS model-zoo? If yes, which model are you using?

**Comment by frankfliu** [comment]
@aikudexiaohai pushed PR to fix our template.
