### ISSUE TITLE
How to enable CORS on mms

### ISSUE THREAD

**Issue by MaxTran96** [awslabs/mxnet-model-server#768]
<img width="506" alt="Screen Shot 2019-03-11 at 8 37 11 AM" src="https://user-images.githubusercontent.com/15274946/54136614-5be1ce00-43d9-11e9-92bd-8a2689950fd4.png">
<img width="930" alt="Screen Shot 2019-03-11 at 8 10 29 AM" src="https://user-images.githubusercontent.com/15274946/54136621-5f755500-43d9-11e9-8c4b-f5172c4f72b9.png">
<img width="438" alt="Screen Shot 2019-03-08 at 4 54 20 AM" src="https://user-images.githubusercontent.com/15274946/54136635-643a0900-43d9-11e9-9aa0-09c93878e790.png">
I'm not sure how to enable CORS on this. Thanks!

**Comment by MaxTran96** [comment]
I have the header request in my code as well a config.properties file that contains those lines of code in the documentation. I still have the error

**Comment by MaxTran96** [comment]
<img width="582" alt="Screen Shot 2019-03-11 at 8 43 19 AM" src="https://user-images.githubusercontent.com/15274946/54136839-bda23800-43d9-11e9-9b05-408e9ec1e248.png">
my config.properties file

**Comment by ddavydenko** [comment]
Hey @MaxTran96 , have you tried to use `*` for the `cors_allowed_origin` value?

**Comment by frankfliu** [comment]
@MaxTran96 

You should not added header "Access-Control-Allow-Origin: *" to your request, browser  should
append "Origin: http://localhost:3001" to the header.
can you capture the request header sent by browser to check if the request was sent properly?

Remember, CORS is doing string match, suggest use "*" for testing.

**Comment by ddavydenko** [comment]
In conversation over slack channel we were able to clarify with @MaxTran96 that he was using axios to send requests. Once he switched to fetch API this issue was resolved for him. I am going to close this issue, @MaxTran96 please feel free to add more details if necessary.
