### ISSUE TITLE
Handle invalid input gracefully

### ISSUE THREAD

**Issue by mikeobr** [awslabs/mxnet-model-server#779]
Given a MMS custom service that expects JSON as input,
If the input is invalid JSON such as `{ "url": "I missed a quote}`
MMS will return 
`{
    "code": 500,
    "type": "InternalServerException",
    "message": "Worker died."
}`

What should instead happen is probably either some 4xx error "could not deserialize input" or somehow allow the custom service to validate/handle erroneous input.

**Comment by vdantu** [comment]
@mikeobr : We are working on a feature to over-ride any preprocessing done on the incoming requests. In that case, the backend worker will get the message as a binary blob, which can be  decoded to 'utf-8' and 'json.loaded' by the backend worker.
