### ISSUE TITLE
Unable to use mkl to accelerate

### ISSUE THREAD

**Issue by Seedlingfish** [awslabs/mxnet-model-server#785]
If you do not use mxnet-model-server and run directly locally, the inference time is very short. If you use mxnet-model-server, the inference time is very long, the same as when you don't use mkl. That is, cannot use mkl acceleration in the service. I don't know why this happened.

**Comment by ddavydenko** [comment]
Hi @Seedlingfish , would you mind providing a bit more details on how to repro your scenario? It is a bit hard to extract from your message what exactly is not working well for you. It would be very useful if you could provide some concrete steps to repro: which OS you are using, which container or pip wheel you used to install MMS, which version of MXNet you are using to run inference directly, what your model is and what data you are using for testing inference.

**Comment by Seedlingfish** [comment]
The environment I am using is awsdeeplearningteam/mxnet-model-server:1.0.2-mxnet-cpu, and the model is resnet50 in mx.gluon.vision.model_zoo. If running locally, the inference time is 0.03s. If running in mxnet-model-ser, the time is 0.1s.

**Comment by Seedlingfish** [comment]
and my config file is:
inference_address = http://0.0.0.0:8089
management_address = http://0.0.0.0:8081
default_workers_per_model = 1
number_of_gpu = 0

**Comment by aikudexiaohai** [comment]
I think the reason is that mkldnn needs to use multiple CPUs to work, and mxnet-model-server uses only one CPU per model, so the speed will be slow.

**Comment by vdantu** [comment]
Where are you running the model server. If it is on your localhost, you can
try setting a larger number for OMP_NUM_THREADS variable. Set it to number
of CPUs you have and see how it works for you.

If you have more than 1 worker, it's not advisable to set this value high.

**Comment by aikudexiaohai** [comment]
@Seedlingfish @vdantu thanks!
I also encountered the same problem. When I set the OMP_NUM_THREADS environment variable, the model can use multiple cores to inference.

**Comment by vdantu** [comment]
@aikudexiaohai : So the solution to your problem was "OMP_NUM_THREADS" ? Thats a double edged sword. 
If you are optimizing for Latency, have less number of `model workers` and more value for "OMP_NUM_THREADS". 
If you are optimizing your server for throughput, its better to have more `model workers` and smaller value (or even just unsetting the env var) `OMP_NUM_THREADS`.

**Comment by aikudexiaohai** [comment]
@vdantu Ok, I will weigh it

**Comment by vdantu** [comment]
@Seedlingfish : Does modifying "OMP_NUM_THREADS" help?

**Comment by Seedlingfish** [comment]
@vdantu Yes, It works for me.Thanks a lot.
