### ISSUE TITLE
Added value of using MMS compared to custom docker image?

### ISSUE THREAD

**Issue by henningsway** [awslabs/mxnet-model-server#815]
First of all, thank you for developing a flexible and open serving-framework.

In my current use-case I need to serve a ML-model asynchronously, with the events being handled by a message broker. Currently the ML-model is part of a docker-image, which bundles the python dependencies and loads and serves the model artifact. The process isn't perfect, but it works.

What would be the main benefits of handing the serving-task to `MMS` (or any serving-framework), especially since another REST-call would to be made?

(I suppose, it could be conventions (e.g. *.MAR), performance, metrics? What am I missing?)

Would be very happy to benefit from your insight and experience regarding this matter. :)

**Comment by vdantu** [comment]
MMS as a whole brings in a lot of features. Apart from the ones you mentioned  ie., custom model metrics, logs, packaging all model artifacts, it also brings in features such as
1. Managing the full lifecycle of the models through control plane APIs
2. Scaling in and scaling out of your model instances to handle multiple requests at the same time. This goes hand in hand with performance I guess.
3. Keeps these model instances up and running and is responsible for this high availability.
4. REST APIs to make these calls convenient.
5. Queuing the requests and scheduling it on workers.

If you package just the model in the container, you would need to write an orchestrator and a server to handle multiple connections coming in, handle the requests, maintain high availability etc. 

I am not sure if this answers your question. Please do let me know if you need any further information :)

**Comment by henningsway** [comment]
This is perfect, thank you!
