### ISSUE TITLE
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 4194304 byte(s) of direct memory 

### ISSUE THREAD

**Issue by Asher-1** [awslabs/mxnet-model-server#831]
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 4194304 byte(s) of direct memory

**Comment by swayam18** [comment]
We are also seeing a similar error on the latest version:

`2019-07-22 10:51:32,851 [ERROR] pollEventLoopGroup-3-3 com.amazonaws.ml.mms.http.HttpRequestHandler -
io.netty.util.internal.OutOfDirectMemoryError: failed to allocate 65536 byte(s) of direct memory (used: 10429447, max: 10485760)`

**Comment by swayam18** [comment]
Increasing the direct memory as specified here did the trick: https://github.com/awslabs/mxnet-model-server/blob/master/docs/configuration.md

We have bumped this number to 512mb.

**Comment by Asher-1** [comment]
thank you , it works

**Comment by vdantu** [comment]
Since this was fixed, I will go ahead and close the issue. Please feel free to reopen it if you see this further :)
