### ISSUE TITLE
how can I send back application/json as content type?

### ISSUE THREAD

**Issue by xuweidongkobe** [awslabs/mxnet-model-server#846]
I am using MMS to server a pytorch model, and I wonder that how can I return a application/json form data rather than application/octet-stream?

**Comment by vdantu** [comment]
@xuweidongkobe : Did this solve your issue? If yes, please feel free to close this issue :)

**Comment by vdantu** [comment]
@xuweidongkobe : I will close the issue for now. Please feel free if you still have this question.

**Comment by xuweidongkobe** [comment]
For some reason ,I am using mxnet-model-server (1.0.4), which version has no "set_response_header" proprety, but has "set_response_content_type" property,   I add a line "context.set_response_content_type(0, 'application/json')" in custom service entry point function, but it not wokrs.  Can you tell me how to solve the problem, thank you?

**Comment by xuweidongkobe** [comment]
For some reason ,I am using mxnet-model-server (1.0.4), which version has no "set_response_header" proprety, but has "set_response_content_type" property, I add a line "context.set_response_content_type(0, 'application/json')" in custom service entry point function, but it not wokrs. Can you tell me how to solve the problem, thank you?
